services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - stock-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/stockmanager}
      RUST_LOG: ${RUST_LOG:-stock_web_server=debug,actix_web=info}
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-8080}
      JWT_SECRET: ${JWT_SECRET:-your_secret_key_here}
      ENABLE_REGISTRATION: ${ENABLE_REGISTRATION:-false}
    ports:
      - "${PORT:-8080}:8080"
    networks:
      - stock-network
    depends_on:
      db:
        condition: service_healthy

networks:
  stock-network:
    driver: bridge

volumes:
  postgres_data:
