[package]
name = "stock-web-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = { workspace = true }
actix-rt = { workspace = true }
actix-web = { workspace = true }
anyhow = { workspace = true }
askama = { workspace = true }
askama_actix = "0.14"
diesel = { workspace = true }
stock-application = { path = "../application" }
stock-domain = { path = "../domain" }
stock-infrastructure = { path = "../infrastructure" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
